version: '3.10'

services:
  python-demo:
    image: python-docker-demo:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: python-sagar-demo
    stdin_open: true
    tty: true
    command: python main.py
